version: '3.0'
services:
  store-app:
    image: store-app
    container_name: store-app
    hostname: store-app
    ports:
     - "3000:3000"
    environment:
      - SERVER_HOST=http://localhost:8080/store
      - NODE_ENV= production
      - HOST=0.0.0.0
      



