version: '3.0'
services:
  store-app:
    image: store-app
    container_name: store-app
    hostname: store-app
    ports:
     - "8084:8080"
    environment:
      - SERVER_HOST=http://${COMPUTERNAME}:8080



