apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-boot-app
  labels:
    app: spring-boot-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: spring-boot-app
  template:
    metadata:
      labels:
        app: spring-boot-app
    spec:
      containers:
      - name: spring-boot-app
        image: localhost:5000/spring-boot-app
        ports:
        - containerPort: 8080
        env:
          - name: "HOST_DB"
            value: "sql-server-store"
          - name: "USER_DB"
            value: "sa"
          - name: "PWD_DB"
            value: "123456qwe!"
        volumeMounts:
          - name: images
            mountPath: /content/images
      volumes:
        - name: images
          hostPath:
            path: /images