apiVersion: apps/v1
kind: Deployment
metadata:
  name: store-app
  labels:
    app: store-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: store-app
  template:
    metadata:
      labels:
        app: store-app
    spec:
      containers:
      - name: store-app
        image: localhost:5000/store-app
        ports:
        - containerPort: 8080